'use client';

import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { toast } from 'sonner';
import { Loader2, CalendarCheck, ArrowLeft, Search, MoreHorizontal, CheckCircle2, XCircle, RefreshCw, Clock } from 'lucide-react';
import { format } from 'date-fns';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import Link from 'next/link';

interface MeetingResult {
    id: string;
    clinic_name: string;
    phone_number: string;
    city: string;
    meeting_date: string;
    meeting_time: string;
    meeting_status: string;
    meeting_notes: string;
    sdr_name?: string;
    created_at: string;
}

export default function MeetingsPage() {
    const [meetings, setMeetings] = useState<MeetingResult[]>([]);
    const [loading, setLoading] = useState(true);
    const [searchQuery, setSearchQuery] = useState('');
    const [userRole, setUserRole] = useState<string | null>(null);

    // Modal State
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [selectedMeeting, setSelectedMeeting] = useState<MeetingResult | null>(null);
    const [updating, setUpdating] = useState(false);
    const [newStatus, setNewStatus] = useState<string>('');
    const [followUpDate, setFollowUpDate] = useState<string>('');
    const [reminderNote, setReminderNote] = useState<string>('');

    useEffect(() => {
        fetchProfile();
        fetchMeetings();
    }, []);

    const fetchProfile = async () => {
        try {
            const res = await fetch('/api/auth/me');
            const data = await res.json();
            if (data.user) setUserRole(data.user.role);
        } catch (e) { }
    };

    const fetchMeetings = async () => {
        setLoading(true);
        try {
            const res = await fetch('/api/meetings/list');
            if (res.ok) {
                const data = await res.json();
                setMeetings(data.meetings || []);
            } else {
                toast.error('Failed to load meetings list');
            }
        } catch (e) {
            toast.error('Network error while fetching meetings');
        } finally {
            setLoading(false);
        }
    };

    const handleUpdateStatus = async () => {
        if (!selectedMeeting || !newStatus) return;

        setUpdating(true);
        try {
            const res = await fetch('/api/meetings/update-status', {
                method: 'PATCH',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    meetingId: selectedMeeting.id,
                    status: newStatus,
                    followUpDate,
                    reminderNote
                })
            });

            if (res.ok) {
                toast.success('Meeting status updated successfully');
                setIsModalOpen(false);
                fetchMeetings();
            } else {
                const data = await res.json();
                toast.error(data.error || 'Failed to update status');
            }
        } catch (e) {
            toast.error('Network error while updating status');
        } finally {
            setUpdating(false);
        }
    };

    const openStatusModal = (meeting: MeetingResult) => {
        setSelectedMeeting(meeting);
        setNewStatus(meeting.meeting_status);
        setFollowUpDate(new Date().toISOString().split('T')[0]);
        setReminderNote('');
        setIsModalOpen(true);
    };

    const filteredMeetings = meetings.filter(meeting => {
        if (!searchQuery) return true;
        const q = searchQuery.toLowerCase();
        return (
            (meeting.clinic_name?.toLowerCase().includes(q)) ||
            (meeting.city?.toLowerCase().includes(q)) ||
            (meeting.phone_number?.toLowerCase().includes(q))
        );
    });

    return (
        <div className="min-h-screen bg-slate-50 dark:bg-slate-950 p-6 relative">
            <div className="max-w-7xl mx-auto space-y-6">

                {/* Header */}
                <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white dark:bg-slate-900 p-4 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800">
                    <div>
                        <h1 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-slate-100 flex items-center gap-2">
                            <CalendarCheck className="h-6 w-6 text-green-600" />
                            Scheduled Appointments List
                        </h1>
                        <p className="text-sm text-slate-500 mt-1">Finalized bookings and scheduled meetings generated by the SDR team.</p>
                    </div>

                    <div className="w-full md:w-72 relative">
                        <Input
                            placeholder="Search clinic, city, or phone..."
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            className="pl-9 bg-slate-50 dark:bg-slate-950 border-slate-200 dark:border-slate-800"
                        />
                        <Search className="w-4 h-4 absolute left-3 top-3 text-slate-400" />
                    </div>
                </div>

                {/* Data Table */}
                <Card className="shadow-sm border-slate-200 dark:border-slate-800 overflow-hidden ring-1 ring-slate-200 dark:ring-slate-800">
                    <div className="overflow-x-auto">
                        <table className="w-full text-sm text-left border-collapse min-w-[1000px]">
                            <thead className="bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 font-semibold border-b border-slate-200 dark:border-slate-700">
                                <tr>
                                    <th className="px-6 py-4 whitespace-nowrap">Date Booked On</th>
                                    <th className="px-6 py-4 whitespace-nowrap">Clinic Name</th>
                                    <th className="px-6 py-4 whitespace-nowrap">Phone / City</th>
                                    <th className="px-6 py-4 whitespace-nowrap">Booked By</th>
                                    <th className="px-6 py-4 text-center whitespace-nowrap">Meeting Date</th>
                                    <th className="px-6 py-4 text-center whitespace-nowrap">Time</th>
                                    <th className="px-6 py-4 text-center whitespace-nowrap">Status</th>
                                    <th className="px-6 py-4 text-center whitespace-nowrap">Notes / Reminder</th>
                                    {(userRole === 'ADMIN' || userRole === 'MANAGER') && (
                                        <th className="px-6 py-4 text-center whitespace-nowrap">Actions</th>
                                    )}
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-100 dark:divide-slate-800 bg-white dark:bg-slate-900">
                                {loading ? (
                                    <tr>
                                        <td colSpan={7} className="px-6 py-12 text-center text-slate-500 whitespace-nowrap">
                                            <Loader2 className="h-6 w-6 animate-spin mx-auto mb-2" />
                                            Loading scheduled meetings...
                                        </td>
                                    </tr>
                                ) : meetings.length === 0 ? (
                                    <tr>
                                        <td colSpan={7} className="px-6 py-12 text-center text-slate-500 whitespace-nowrap">
                                            No meetings booked yet. Generate some leads!
                                        </td>
                                    </tr>
                                ) : filteredMeetings.length === 0 ? (
                                    <tr>
                                        <td colSpan={7} className="px-6 py-12 text-center text-slate-500 whitespace-nowrap">
                                            Your search didn't match any meetings.
                                        </td>
                                    </tr>
                                ) : (
                                    filteredMeetings.map((meeting) => (
                                        <tr
                                            key={meeting.id}
                                            className="hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors"
                                        >
                                            <td className="px-6 py-4 whitespace-nowrap text-slate-500">
                                                {format(new Date(meeting.created_at), 'MMM dd, yyyy')}
                                            </td>
                                            <td className="px-6 py-4 font-bold text-slate-900 dark:text-slate-100 max-w-[200px] truncate whitespace-nowrap" title={meeting.clinic_name}>
                                                {meeting.clinic_name}
                                            </td>
                                            <td className="px-6 py-4 text-slate-600 dark:text-slate-400 whitespace-nowrap">
                                                <div className="font-mono text-xs">{meeting.phone_number}</div>
                                                <div className="text-xs text-slate-500">{meeting.city}</div>
                                            </td>
                                            <td className="px-6 py-4 text-indigo-600 dark:text-indigo-400 font-medium whitespace-nowrap">
                                                {meeting.sdr_name || 'System'}
                                            </td>
                                            <td className="px-6 py-4 text-center whitespace-nowrap font-medium text-slate-800 dark:text-slate-200">
                                                {format(new Date(meeting.meeting_date), 'MMM dd, yyyy')}
                                            </td>
                                            <td className="px-6 py-4 text-center whitespace-nowrap text-indigo-700 dark:text-indigo-400 font-semibold bg-indigo-50/50 dark:bg-indigo-950/20">
                                                {meeting.meeting_time}
                                            </td>
                                            <td className="px-6 py-4 text-center whitespace-nowrap">
                                                <span className={`px-3 py-1 rounded-full text-xs font-bold whitespace-nowrap ${meeting.meeting_status === 'Scheduled' ? 'bg-green-100 text-green-700 border border-green-200' :
                                                    meeting.meeting_status === 'Show Up' || meeting.meeting_status === 'Completed' ? 'bg-emerald-500 text-white' :
                                                        meeting.meeting_status === 'No Show' ? 'bg-rose-100 text-rose-700 border border-rose-200' :
                                                            meeting.meeting_status === 'Rescheduled' ? 'bg-amber-100 text-amber-700 border border-amber-200' :
                                                                'bg-slate-100 text-slate-600 border border-slate-200'
                                                    }`}>
                                                    {meeting.meeting_status}
                                                </span>
                                            </td>
                                            <td className="px-6 py-4 text-slate-600 dark:text-slate-400 max-w-[250px] italic text-xs">
                                                {meeting.meeting_notes || '-'}
                                            </td>
                                            {(userRole === 'ADMIN' || userRole === 'MANAGER') && (
                                                <td className="px-6 py-4 text-center whitespace-nowrap">
                                                    <Button
                                                        variant="outline"
                                                        size="sm"
                                                        className="h-8 w-8 p-0"
                                                        onClick={() => openStatusModal(meeting)}
                                                    >
                                                        <MoreHorizontal className="h-4 w-4" />
                                                    </Button>
                                                </td>
                                            )}
                                        </tr>
                                    ))
                                )}
                            </tbody>
                        </table>
                    </div>
                </Card>

                {/* Status Update Modal */}
                <Dialog open={isModalOpen} onOpenChange={setIsModalOpen}>
                    <DialogContent className="sm:max-w-[425px]">
                        <DialogHeader>
                            <DialogTitle className="flex items-center gap-2">
                                <RefreshCw className="h-5 w-5 text-indigo-600" />
                                Update Meeting Status
                            </DialogTitle>
                        </DialogHeader>
                        <div className="space-y-4 py-4">
                            <div className="space-y-2">
                                <label className="text-sm font-medium">New Status</label>
                                <Select value={newStatus} onValueChange={setNewStatus}>
                                    <SelectTrigger>
                                        <SelectValue placeholder="Select status" />
                                    </SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="Scheduled">Scheduled</SelectItem>
                                        <SelectItem value="Show Up">Show Up / Completed</SelectItem>
                                        <SelectItem value="No Show">No Show</SelectItem>
                                        <SelectItem value="Rescheduled">Rescheduled</SelectItem>
                                        <SelectItem value="Cancelled">Cancelled</SelectItem>
                                    </SelectContent>
                                </Select>
                            </div>

                            {(newStatus === 'No Show' || newStatus === 'Rescheduled' || newStatus === 'Cancelled') && (
                                <>
                                    <div className="space-y-2">
                                        <label className="text-sm font-medium flex items-center gap-1">
                                            <Clock className="h-3 w-3" />
                                            SDR Follow-up Date
                                        </label>
                                        <Input
                                            type="date"
                                            value={followUpDate}
                                            onChange={(e) => setFollowUpDate(e.target.value)}
                                        />
                                        <p className="text-[10px] text-slate-500 italic">
                                            This lead will be moved back to active queue for follow-up on this date.
                                        </p>
                                    </div>
                                    <div className="space-y-2">
                                        <label className="text-sm font-medium">Reminder Note for SDR</label>
                                        <textarea
                                            className="w-full h-24 p-3 text-sm border rounded-md dark:bg-slate-900 focus:ring-2 focus:ring-indigo-500 outline-none"
                                            placeholder="Ask SDR to double check phone number or try another time..."
                                            value={reminderNote}
                                            onChange={(e) => setReminderNote(e.target.value)}
                                        />
                                    </div>
                                </>
                            )}
                        </div>
                        <DialogFooter>
                            <Button variant="ghost" onClick={() => setIsModalOpen(false)}>Cancel</Button>
                            <Button
                                className="bg-indigo-600 hover:bg-indigo-700"
                                onClick={handleUpdateStatus}
                                disabled={updating}
                            >
                                {updating ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : null}
                                Update Status
                            </Button>
                        </DialogFooter>
                    </DialogContent>
                </Dialog>
            </div>
        </div>
    );
}
