'use client';

import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { toast } from 'sonner';
import { Loader2, CalendarCheck, ArrowLeft } from 'lucide-react';
import { format } from 'date-fns';
import Link from 'next/link';

interface MeetingResult {
    id: string;
    clinic_name: string;
    phone_number: string;
    city: string;
    meeting_date: string;
    meeting_time: string;
    meeting_status: string;
    meeting_notes: string;
    created_at: string;
}

export default function MeetingsPage() {
    const [meetings, setMeetings] = useState<MeetingResult[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetchMeetings();
    }, []);

    const fetchMeetings = async () => {
        setLoading(true);
        try {
            const res = await fetch('/api/meetings/list');
            if (res.ok) {
                const data = await res.json();
                setMeetings(data.meetings || []);
            } else {
                toast.error('Failed to load meetings list');
            }
        } catch (e) {
            toast.error('Network error while fetching meetings');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="min-h-screen bg-slate-50 dark:bg-slate-950 p-6 relative">
            <div className="max-w-7xl mx-auto space-y-6">

                {/* Header */}
                <div className="flex justify-between items-center bg-white dark:bg-slate-900 p-4 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800">
                    <div>
                        <h1 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-slate-100 flex items-center gap-2">
                            <CalendarCheck className="h-6 w-6 text-green-600" />
                            Meeting Results
                        </h1>
                        <p className="text-sm text-slate-500 mt-1">Finalized bookings and scheduled meetings generated by the SDR team.</p>
                    </div>
                </div>

                {/* Data Table */}
                <Card className="shadow-sm border-slate-200 dark:border-slate-800 overflow-hidden">
                    <div className="overflow-x-auto">
                        <table className="w-full text-sm text-left">
                            <thead className="bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 font-semibold border-b border-slate-200 dark:border-slate-700">
                                <tr>
                                    <th className="px-6 py-4">Date Booked On</th>
                                    <th className="px-6 py-4">Clinic Name</th>
                                    <th className="px-6 py-4">Phone / City</th>
                                    <th className="px-6 py-4 text-center">Meeting Date</th>
                                    <th className="px-6 py-4 text-center">Time</th>
                                    <th className="px-6 py-4 text-center">Status</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-100 dark:divide-slate-800 bg-white dark:bg-slate-900">
                                {loading ? (
                                    <tr>
                                        <td colSpan={6} className="px-6 py-12 text-center text-slate-500">
                                            <Loader2 className="h-6 w-6 animate-spin mx-auto mb-2" />
                                            Loading scheduled meetings...
                                        </td>
                                    </tr>
                                ) : meetings.length === 0 ? (
                                    <tr>
                                        <td colSpan={6} className="px-6 py-12 text-center text-slate-500">
                                            No meetings booked yet. Generate some leads!
                                        </td>
                                    </tr>
                                ) : (
                                    meetings.map((meeting) => (
                                        <tr
                                            key={meeting.id}
                                            className="hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors"
                                        >
                                            <td className="px-6 py-4 whitespace-nowrap text-slate-500">
                                                {format(new Date(meeting.created_at), 'MMM dd, yyyy')}
                                            </td>
                                            <td className="px-6 py-4 font-bold text-slate-900 dark:text-slate-100 max-w-[200px] truncate" title={meeting.clinic_name}>
                                                {meeting.clinic_name}
                                            </td>
                                            <td className="px-6 py-4 text-slate-600 dark:text-slate-400">
                                                <div className="font-mono text-xs">{meeting.phone_number}</div>
                                                <div className="text-xs text-slate-500">{meeting.city}</div>
                                            </td>
                                            <td className="px-6 py-4 text-center whitespace-nowrap font-medium text-slate-800 dark:text-slate-200">
                                                {format(new Date(meeting.meeting_date), 'MMM dd, yyyy')}
                                            </td>
                                            <td className="px-6 py-4 text-center whitespace-nowrap text-indigo-700 dark:text-indigo-400 font-semibold bg-indigo-50/50 dark:bg-indigo-950/20">
                                                {meeting.meeting_time}
                                            </td>
                                            <td className="px-6 py-4 text-center">
                                                <span className={`px-3 py-1 rounded-full text-xs font-bold ${meeting.meeting_status === 'Scheduled' ? 'bg-green-100 text-green-700 border border-green-200' : 'bg-slate-100 text-slate-600 border border-slate-200'}`}>
                                                    {meeting.meeting_status}
                                                </span>
                                            </td>
                                        </tr>
                                    ))
                                )}
                            </tbody>
                        </table>
                    </div>
                </Card>
            </div>
        </div>
    );
}
